name: napapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^17.0.0
  flutter_foreground_task: ^8.17.0
  table_calendar: ^3.1.2
  provider: ^6.1.5
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  bottom_navy_bar: ^6.1.0
  calendar_date_picker2: ^2.0.1
  fl_chart: ^1.2.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.5
  intl:
  http:
  flutter_alarm_clock: ^0.1.2
  duration_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/sleep_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/sleep_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/sleep_icon.png
    - assets/profile_imm/